version: 0.2

phases :
  pre_build : 
    commands :
      - echo Logging into AWS ECR
      - aws --version
      - $(aws ecr get-login-password --region ap-southeast-1)
      - REPOSITORY_URI=427554361065.dkr.ecr.ap-southeast-1.amazonaws.com/devops-test
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  
  
  build :
    commands :
      - echo build started on 'date'
      - echo Building the Docker Image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      
  post_build :
    commands :
      - echo build complete on 'date'
      - echo Pushing the docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file....
      - printf '[{"name":"devops-test","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts :
  files : imagedefinitions.json
